#!/usr/bin/env bash
# collect-facts.sh — deterministic fact collector for the basis-principles-audit skill.
#
# Read-only: prints a markdown fact sheet to stdout, writes nothing.
# Zero dependencies beyond coreutils + grep + awk + find.
#
# Usage: bash collect-facts.sh [repo-root]
#
# The fact sheet is the evidence floor for the audit: every number and path in it
# is mechanically derived, so the scoring model never has to (and never gets to)
# invent inventory facts. Judgment stays with the model; counting stays here.

set -uo pipefail

ROOT="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$ROOT" || { echo "collect-facts: cannot cd to $ROOT" >&2; exit 1; }

# Directories never worth scanning.
PRUNE=( -name .git -o -name node_modules -o -name .venv -o -name venv
        -o -name dist -o -name build -o -name __pycache__ -o -name worktrees
        -o -name .next -o -name coverage -o -name .pytest_cache -o -name .ruff_cache
        -o -name .obsidian -o -name .trash )

findx() { # findx <find-predicates...> — find with standard prunes
  find . \( \( "${PRUNE[@]}" \) -prune \) -o \( "$@" \) -print 2>/dev/null | sed 's|^\./||' | sort
}

rel_lines() { wc -l < "$1" 2>/dev/null | tr -d ' '; }

echo "# Fact sheet — $(basename "$ROOT")"
echo
echo "Generated by \`collect-facts.sh\` (deterministic; regenerate rather than edit)."
echo "Working directory: \`$ROOT\`"
echo

# ---------------------------------------------------------------- 1. context files
echo "## 1. Agent context files"
echo
CONTEXT_FILES=$(findx \( -type f -o -type l \) \( -name CLAUDE.md -o -name AGENTS.md -o -name agents.md -o -name CLAUDE.local.md \) | grep -vE '(_archive|/templates?)/' || true)
# Real files only (symlinks resolve to a file already in the list) — used by
# scans where a symlink+target pair must count as ONE source, not two.
CONTEXT_FILES_REAL=$(while IFS= read -r f; do [ -n "$f" ] && [ ! -L "$f" ] && echo "$f"; done <<< "$CONTEXT_FILES")
if [ -z "$CONTEXT_FILES" ]; then
  echo "None found."
else
  echo "| Path | Lines | Symlink → | Frontmatter |"
  echo "|------|------:|-----------|:-----------:|"
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    lines=$(rel_lines "$f")
    if [ -L "$f" ]; then
      link=$(readlink "$f")
    else
      link="—"
      # Windows checkouts (core.symlinks=false) materialize committed symlinks as
      # one-line files holding the target path — flag likely cases for the auditor.
      if [ "${lines:-0}" -le 1 ]; then
        first=$(head -n 1 "$f" 2>/dev/null)
        case "$first" in
          ''|*[!A-Za-z0-9._/-]*) : ;;
          *) [ -e "$(dirname "$f")/$first" ] && link="$first (materialized symlink?)" ;;
        esac
      fi
    fi
    if [ "$(head -n 1 "$f" 2>/dev/null)" = "---" ]; then fm="yes"; else fm="no"; fi
    echo "| \`$f\` | $lines | $link | $fm |"
  done <<< "$CONTEXT_FILES"
fi
echo

# Sibling check: every dir with a CLAUDE.md should be visible to non-Claude agents too.
echo "### Sibling AGENTS.md coverage (interoperability)"
echo
missing_sibling=0
while IFS= read -r f; do
  [ -z "$f" ] && continue
  case "$f" in *CLAUDE.md) ;; *) continue ;; esac
  d=$(dirname "$f")
  if [ ! -e "$d/AGENTS.md" ] && [ ! -e "$d/agents.md" ]; then
    echo "- \`$d/\` has \`CLAUDE.md\` but no \`AGENTS.md\`/\`agents.md\` alongside"
    missing_sibling=$((missing_sibling + 1))
  fi
done <<< "$CONTEXT_FILES"
[ "$missing_sibling" -eq 0 ] && echo "Every CLAUDE.md has an AGENTS.md sibling (file or symlink)."
echo

echo "### Other agent-tool files (root)"
echo
PROBED=".cursorrules .cursor .windsurfrules .continuerc .github/copilot-instructions.md GEMINI.md .clinerules .rules .roo .codex .junie .aider*"
found_other=0
for t in .cursorrules .cursor .windsurfrules .continuerc .github/copilot-instructions.md \
         GEMINI.md .clinerules .rules .roo .codex .junie; do
  if [ -e "$t" ]; then
    # A real file (not a symlink to canon) is its own source of truth — drift risk.
    if [ -f "$t" ] && [ ! -L "$t" ]; then
      echo "- \`$t\` present — **real file, not a symlink** ($(rel_lines "$t") lines): separate source, check for drift against canon"
    else
      echo "- \`$t\` present"
    fi
    found_other=1
  fi
done
ls .aider* >/dev/null 2>&1 && { echo "- \`.aider*\` present"; found_other=1; }
[ "$found_other" -eq 0 ] && echo "None of the probed set ($PROBED). Other agent-tool conventions may exist — this list is not exhaustive."
echo

# ---------------------------------------------------------------- 2. root context stats
echo "## 2. Root context file stats (default-no signals)"
echo
ROOT_CTX=""
for c in CLAUDE.md AGENTS.md agents.md; do
  [ -f "$c" ] && { ROOT_CTX="$c"; break; }
done
if [ -z "$ROOT_CTX" ]; then
  echo "No root context file."
else
  echo "- Root file: \`$ROOT_CTX\`, $(rel_lines "$ROOT_CTX") lines"
  n_links=$(grep -cE '\]\([^)]+\)' "$ROOT_CTX" 2>/dev/null || true)
  echo "- Markdown links: ${n_links:-0}"
  n_imports=$(grep -cE '(^|[[:space:]])@[A-Za-z0-9_][A-Za-z0-9_./-]*\.(md|txt|json)' "$ROOT_CTX" 2>/dev/null || true)
  echo "- \`@path\` imports (each one force-loads its target every session): ${n_imports:-0}"
  if grep -qiE '^#+ .*(read on demand|reference)' "$ROOT_CTX" 2>/dev/null; then
    echo "- Read-on-demand / Reference section: present"
  else
    echo "- Read-on-demand / Reference section: NOT found (heading grep)"
  fi
fi
echo

# ---------------------------------------------------------------- 3. broken links
echo "## 3. Broken relative links in canon markdown"
echo
echo "Sources scanned: context files + \`docs/\` markdown, excluding \`specs\`, \`_archive\`, \`rfcs\`, \`.notes\` paths (intent/history, not canon)."
echo
DOC_FILES=$(findx -type f -name '*.md' -path './docs/*' | grep -vE '/(specs|_archive|rfcs|\.notes)/' || true)
broken=0
checked=0
while IFS= read -r f; do
  [ -z "$f" ] || [ ! -f "$f" ] && continue
  while IFS= read -r target; do
    [ -z "$target" ] && continue
    case "$target" in
      http://*|https://*|mailto:*|\#*|\<*) continue ;;
    esac
    target="${target%%#*}"          # strip fragment
    target="${target%% \"*}"        # strip optional link title
    [ -z "$target" ] && continue
    checked=$((checked + 1))
    if [ "${target#/}" != "$target" ]; then
      resolved=".${target}"          # leading slash → repo-root relative
    else
      resolved="$(dirname "$f")/$target"
    fi
    if [ ! -e "$resolved" ]; then
      broken=$((broken + 1))
      [ "$broken" -le 40 ] && echo "- \`$f\` → \`$target\` (does not resolve)"
    fi
  done < <(grep -oE '\]\([^)]+\)' "$f" 2>/dev/null | sed -E 's/^\]\(//; s/\)$//')
done <<< "$CONTEXT_FILES_REAL
$DOC_FILES"
[ "$broken" -gt 40 ] && echo "- …and $((broken - 40)) more"
echo
echo "**Total: $broken broken of $checked relative links checked.**"
echo

# ---------------------------------------------------------------- 4. duplicate lines
echo "## 4. Duplicate lines across context files (default-no / canonicality signal)"
echo
echo "Verbatim lines ≥30 chars appearing in two or more context files (headings and table rows excluded; symlinks count as their target, not as a second copy)."
echo
DUPS=$(
  while IFS= read -r f; do
    [ -z "$f" ] || [ ! -e "$f" ] && continue
    awk -v fn="$f" 'length($0) >= 30 {
      line = $0
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
      if (line ~ /^[#|]/) next
      print line "\t" fn
    }' "$f"
  done <<< "$CONTEXT_FILES_REAL" |
  sort -t "$(printf '\t')" -k1,1 |
  awk -F '\t' '{
    if (!( ($1, $2) in seen )) { seen[$1, $2] = 1; cnt[$1]++; files[$1] = (files[$1] ? files[$1] ", " : "") "`" $2 "`" }
  } END {
    for (k in cnt) if (cnt[k] >= 2) printf "- `%s`\n  - in: %s\n", k, files[k]
  }'
)
if [ -z "$DUPS" ]; then echo "None found."; else echo "$DUPS"; fi
echo

# ---------------------------------------------------------------- 5. verification infra
echo "## 5. Verification infrastructure (verifiability inventory)"
echo
if [ -d .github/workflows ]; then
  echo "- CI workflows ($(ls .github/workflows/*.yml .github/workflows/*.yaml 2>/dev/null | wc -l | tr -d ' ')):"
  for w in .github/workflows/*.yml .github/workflows/*.yaml; do
    [ -e "$w" ] && echo "  - \`$w\`"
  done
else
  echo "- No \`.github/workflows/\`"
fi
for h in .pre-commit-config.yaml lefthook.yml .husky .githooks; do
  [ -e "$h" ] && echo "- Hook config: \`$h\` present"
done
for m in Makefile justfile Taskfile.yml; do
  if [ -f "$m" ]; then
    targets=$(grep -oE '^(verify|check|ci|lint|test)[A-Za-z0-9_-]*:' "$m" 2>/dev/null | sed 's/:$//' | tr '\n' ' ')
    echo "- \`$m\` verification-ish targets: ${targets:-none}"
  fi
done
[ -d .claude/hooks ] && echo "- \`.claude/hooks/\`: $(ls .claude/hooks 2>/dev/null | tr '\n' ' ')"
echo

# ---------------------------------------------------------------- 6. specs discipline
echo "## 6. Spec / intent directories (canonicality inventory)"
echo
found_specs=0
for s in docs/specs docs/specs-public specs rfcs docs/rfcs docs/adr adr .notes; do
  if [ -d "$s" ]; then
    found_specs=1
    idx="none"
    [ -f "$s/INDEX.md" ] && idx="INDEX.md"
    [ "$idx" = "none" ] && [ -f "$s/README.md" ] && idx="README.md"
    echo "- \`$s/\` — $(find "$s" -maxdepth 1 -type d 2>/dev/null | tail -n +2 | wc -l | tr -d ' ') subdirs, index: $idx"
  fi
done
[ "$found_specs" -eq 0 ] && echo "No spec/intent directories found."
echo

# ---------------------------------------------------------------- 7. skills inventory
echo "## 7. Skill packages"
echo
SKILLS=$(findx -type f \( -path '*/.claude/skills/*/SKILL.md' -o -path '*/.agents/skills/*/SKILL.md' \))
if [ -z "$SKILLS" ]; then
  echo "None."
else
  echo "$SKILLS" | while IFS= read -r s; do
    [ -n "$s" ] && echo "- \`$s\` ($(rel_lines "$s") lines)"
  done
fi
COMMANDS_DIR=".claude/commands"
[ -d "$COMMANDS_DIR" ] && echo "- \`$COMMANDS_DIR/\`: $(find "$COMMANDS_DIR" -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ') command files (recursive; namespaced subdirectories included)"
echo

# ---------------------------------------------------------------- 8. prior audit runs
echo "## 8. Prior audit runs (for Phase 0 delta)"
echo
# Exclude the skill's own source dirs, wherever they live: `.claude/skills/`,
# a dotfiles-style `claude/skills-optional/`, or a plugin checkout.
PRIOR=$(findx -type d \( -name '*basis-principles-audit*' -o -name '*agent-readiness-audit*' \) | grep -vE '(^|/)skills(-optional)?/' || true)
if [ -z "$PRIOR" ]; then
  echo "None found — this is a baseline run."
else
  echo "$PRIOR" | while IFS= read -r p; do
    [ -n "$p" ] && echo "- \`$p/\`"
  done
  echo
  echo "Most recent (by path sort) is usually the last entry; confirm by date in the dir name."
fi
echo
echo "---"
echo "End of fact sheet. Facts above are mechanical; interpretation belongs to the audit."
