// @ts-check
import { defineConfig, fontProviders } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
	site: 'https://docs.gettidings.com',
	server: { host: true },
	// Astro 6 deprecated `markdown.gfm`/`smartypants` and leaves them undefined;
	// the built-in `.md` processor still defaults them on, but Starlight 0.38's
	// bundled @astrojs/mdx 5.x reads `config.markdown.gfm` directly and treats
	// undefined as OFF — so `.mdx` pages silently lose GFM (tables render as
	// literal pipes). Set both explicitly until Starlight ships an Astro-6-aware
	// MDX integration; remove then.
	markdown: {
		gfm: true,
		smartypants: true,
	},
	vite: {
		plugins: [tailwindcss()],
	},
	// Fonts are downloaded at build time and served from our own origin with
	// content-hashed, immutable filenames — no fonts.googleapis.com /
	// fonts.gstatic.com request at runtime. Two reasons:
	//   1. FOUT. The old <link> went to a third party, so the font sat behind a
	//      DNS + TLS + CSS round-trip and could not land before first paint:
	//      the wordmark painted its fallback and visibly reflowed (104.52px ->
	//      111.58px) when Source Serif 4 arrived. Served from our own origin and
	//      preloaded, it now arrives before first paint and the wordmark paints
	//      once at its final width.
	//      Astro additionally derives a metrics-matched fallback @font-face
	//      (size-adjust / ascent-override / descent-override, via capsize) that
	//      shrinks the reflow to ~1px if the swap does happen on a slow link.
	//      Caveat worth knowing before trusting it: that face is `src:
	//      local("Times New Roman")`, so it only applies where Times New Roman
	//      is actually installed (Windows/macOS). On a Linux box without the MS
	//      core fonts it is skipped and the stack falls through to Georgia, so
	//      the full ~7px reflow remains there on a slow connection.
	//   2. No third-party request from a project whose pitch is that your data
	//      does not leave your machine (docs/brand/positioning.md).
	// Families/weights mirror the token stacks in frontend/src/index.css. Only
	// `normal` is requested: the old Google URL asked for `opsz,wght` with no
	// `ital` axis, so today's `.tidings-hero h1 em` italic is synthesized —
	// pulling a real italic here would silently change how the hero renders.
	// The generated CSS variables are mapped back onto the Tidings --font-*
	// tokens in src/styles/starlight-overrides.css (the token files themselves
	// are generated by scripts/sync-tokens.mjs and must not be hand-edited).
	fonts: [
		{
			name: 'Source Serif 4',
			cssVariable: '--font-source-serif-4',
			provider: fontProviders.google(),
			weights: [400, 500, 600],
			styles: ['normal'],
			fallbacks: ['Georgia', 'Times New Roman', 'serif'],
			// Source Serif 4 is optically sized, and the old Google URL asked for
			// `opsz,wght@8..60,...`. Without this, Astro fetches the wght axis only
			// and opsz pins to its default, which renders visibly wider glyphs
			// (the 20px wordmark measured 119.39px instead of 111.58px). Keeping
			// the 8..60 range lets font-optical-sizing:auto pick opsz per size, as
			// it does today.
			options: {
				experimental: {
					variableAxis: {
						opsz: [['8', '60']],
					},
				},
			},
		},
		{
			name: 'Inter',
			cssVariable: '--font-inter',
			provider: fontProviders.google(),
			weights: [400, 500, 600, 700],
			styles: ['normal'],
			fallbacks: ['system-ui', 'sans-serif'],
		},
		{
			name: 'JetBrains Mono',
			cssVariable: '--font-jetbrains-mono',
			provider: fontProviders.google(),
			weights: [400, 500],
			styles: ['normal'],
			fallbacks: ['ui-monospace', 'Menlo', 'monospace'],
		},
	],
	integrations: [
		react(),
		starlight({
			title: 'Tidings docs',
			description:
				'A private finance journal from the transaction emails you already receive.',
			logo: {
				src: './src/assets/logo.svg',
				alt: '',
			},
			components: {
				PageTitle: './src/overrides/PageTitle.astro',
				Hero: './src/overrides/Hero.astro',
				// Emits the self-hosted @font-face rules (see `fonts` above).
				Head: './src/overrides/Head.astro',
			},
			social: [
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/tvhahn/tidings',
				},
			],
			customCss: [
				'./src/styles/tidings.css',
				'./src/styles/starlight-overrides.css',
			],
			// Starlight toggles dark mode via [data-theme='dark']; Tidings tokens
			// activate via a `.dark` class. Mirror one to the other on every page.
			// The same script pins data-palette to warm-paper — the app's default
			// (DEFAULT_PALETTE in frontend/src/stores/theme.ts) — so the docs chrome
			// matches the product and the screenshots embedded in it. The docs site
			// has no palette picker; this is a constant, not a preference.
			head: [
				// Fonts are self-hosted via the top-level `fonts` config and
				// emitted by src/overrides/Head.astro — no <link> to Google here.
				//
				// Default social/OG image. Starlight already emits per-page
				// og:title/og:description/canonical and twitter:card
				// summary_large_image, but no image unless one is provided.
				// Absolute URL: unfurl scrapers do not resolve relative og:image
				// reliably. Card asset: regenerate with `pnpm og:images` (frontend/).
				{
					tag: 'meta',
					attrs: { property: 'og:image', content: 'https://docs.gettidings.com/og-image.png' },
				},
				{
					tag: 'meta',
					attrs: { name: 'twitter:image', content: 'https://docs.gettidings.com/og-image.png' },
				},
				{
					tag: 'script',
					content: `
						(function () {
							document.documentElement.dataset.palette = 'warm-paper';
							var sync = function () {
								var dark = document.documentElement.dataset.theme === 'dark';
								document.documentElement.classList.toggle('dark', dark);
							};
							sync();
							new MutationObserver(sync).observe(document.documentElement, {
								attributes: true,
								attributeFilter: ['data-theme'],
							});
						})();
					`,
				},
			],
			sidebar: [
				{ label: 'Welcome', slug: 'index' },
				{ label: 'Quickstart', slug: 'quickstart' },
				{ label: 'Tour', slug: 'tour' },
				{ label: 'Coming from another tool', slug: 'switching' },
				{
					label: 'Getting started',
					items: [
						{ label: 'Docker setup', slug: 'self-hosting/docker' },
						{ label: 'Set up email (IMAP)', slug: 'self-hosting/email' },
						{ label: 'Set up notifications', slug: 'notifications' },
					],
				},
				{
					label: 'Using Tidings',
					items: [
						{ label: 'How Tidings works', slug: 'using/how-it-works' },
						{ label: 'Journal', slug: 'using/journal' },
						{ label: 'Transactions', slug: 'using/transactions' },
						{ label: 'Categorization', slug: 'using/categorization' },
						{ label: 'Needs review', slug: 'using/needs-review' },
						{ label: 'Summary', slug: 'using/summary' },
						{ label: 'Budgets', slug: 'using/budgets' },
						{ label: 'Insights', slug: 'using/insights' },
						{ label: 'Merchants', slug: 'using/merchants' },
						{ label: 'Income statement', slug: 'using/income-statement' },
						{ label: 'Statements', slug: 'using/statements' },
						{ label: 'Tax receipts', slug: 'using/tax' },
						{ label: 'Settings', slug: 'using/settings' },
					],
				},
				{
					label: 'Running it',
					items: [
						{ label: 'Configuration', slug: 'configuration' },
						{ label: 'Backup and restore', slug: 'backup-and-restore' },
						{ label: 'Upgrading', slug: 'upgrading' },
						{ label: 'Troubleshooting', slug: 'troubleshooting' },
						{ label: 'FAQ', slug: 'faq' },
					],
				},
				{
					label: 'Advanced (AWS)',
					items: [
						{ label: 'Email-to-S3 setup', slug: 'self-hosting/email-to-s3' },
						{ label: 'Lambda deployment', slug: 'self-hosting/aws' },
						{ label: 'S3 backup', slug: 's3-backup' },
					],
				},
				{
					label: 'Contributing',
					items: [
						{ label: 'Add a parser', slug: 'add-a-parser' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'Architecture', slug: 'architecture' },
						{ label: 'Agent access', slug: 'agent-access' },
						{ label: 'Tidings for agents', slug: 'for-agents' },
						{ label: 'API reference', slug: 'api' },
						{ label: 'More guides', slug: 'guides' },
					],
				},
			],
		}),
	],
});
