"""Allowlist of lucide icon names permitted as category-icon overrides.

Kept in sync with frontend/src/lib/iconCatalog.ts. A parity test
(tests/unit/test_category_icons_parity.py) guards drift.
"""

ALLOWED_ICON_NAMES: frozenset[str] = frozenset(
    {
        # Food & Drink
        "Utensils",
        "Coffee",
        "Pizza",
        "Beef",
        "Sandwich",
        "Salad",
        "IceCream",
        "Cookie",
        "Wine",
        "Beer",
        "Apple",
        "Soup",
        "Croissant",
        "Cake",
        "ChefHat",
        # Transport
        "Car",
        "CarFront",
        "Fuel",
        "Plane",
        "Train",
        "TramFront",
        "Bus",
        "Bike",
        "Ship",
        "Truck",
        "MapPin",
        "ParkingCircle",
        # Home
        "Home",
        "Building",
        "Building2",
        "BedDouble",
        "Bath",
        "Sofa",
        "Armchair",
        "Lamp",
        "Refrigerator",
        "WashingMachine",
        "Microwave",
        "DoorOpen",
        "Key",
        "Warehouse",
        # Money
        "DollarSign",
        "CreditCard",
        "Banknote",
        "Landmark",
        "Wallet",
        "Receipt",
        "PiggyBank",
        "Coins",
        "Calculator",
        "TrendingUp",
        "TrendingDown",
        "Scale",
        # Shopping
        "ShoppingCart",
        "ShoppingBag",
        "Store",
        "Gift",
        "Tag",
        "Package",
        "Shirt",
        "Footprints",
        "Glasses",
        "Watch",
        # Tech
        "Laptop",
        "Smartphone",
        "Monitor",
        "Wifi",
        "Phone",
        "Headphones",
        "Gamepad2",
        "Printer",
        "Camera",
        "Tv",
        "Cable",
        "Keyboard",
        # People
        "User",
        "Users",
        "Baby",
        "Dog",
        "Cat",
        "Heart",
        "HandHeart",
        "UserPlus",
        "Contact",
        "PersonStanding",
        # Health
        "Stethoscope",
        "HeartPulse",
        "Pill",
        "Syringe",
        "Activity",
        "Hospital",
        "Ambulance",
        "Brain",
        "Dumbbell",
        "Sparkles",
        # Leisure
        "Film",
        "Music",
        "Music2",
        "Guitar",
        "Book",
        "Palette",
        "Trophy",
        "Tent",
        "Globe",
        "Map",
        "Ticket",
        "PartyPopper",
        # Work & Education
        "Briefcase",
        "GraduationCap",
        "FileText",
        "Notebook",
        "Pencil",
        "PenTool",
        "School",
        "Library",
        "Clipboard",
        "Calendar",
        # Utilities & Other
        "Zap",
        "Lightbulb",
        "Droplet",
        "Flame",
        "Hammer",
        "Wrench",
        "Scissors",
        "Brush",
        "Shield",
        "Lock",
        "Settings",
        "Clock",
        "Star",
        "Repeat",
        "MoreHorizontal",
    }
)
