"""Protocol definitions for the six dual-backend service interfaces.

Using Protocol (structural subtyping) rather than ABC means:
  - Static type checkers (mypy, pyright) verify API compliance without
    requiring explicit inheritance in both backends.
  - Agents can read this single file to understand the full contract for
    every service in the system.

Import example:
    from src.finance.protocols import ITransactionsDB
    def get_transactions_db() -> ITransactionsDB: ...
"""

from collections.abc import Mapping, Sequence
from decimal import Decimal
from typing import Any, Protocol, TypedDict, runtime_checkable


class _TransactionItemCore(TypedDict):
    """The two composite-key attributes present on every transaction row.

    ``ForwardedTo`` (partition) and ``DateFileName`` (sort) are required: both
    backends always write them (DynamoDB item build; SQLite ``NOT NULL`` PK
    columns), and even the narrowest projections — the DynamoDB
    ``scan_by_category`` ``ProjectionExpression`` and ``TRANSACTION_LIST_PROJECTION``
    — carry both. Splitting them into a required core (vs. the ``total=False``
    extension below) legalizes ``item["ForwardedTo"]`` / ``item["DateFileName"]``
    subscripts without a ``reportTypedDictNotRequiredAccess`` error.
    """

    ForwardedTo: str
    DateFileName: str


class TransactionItem(_TransactionItemCore, total=False):
    """A transaction row as stored — PascalCase, DynamoDB-shaped.

    Both backends return this shape (`SQLite` via ``row_to_item``); every key
    below is ``total=False`` because projections and older rows omit them (the
    two always-present key attributes live on ``_TransactionItemCore``). Nested
    audit dicts stay loose (``dict[str, Any]``) at this ratchet stage — do not
    chase nested typing.
    """

    FileName: str
    Date: str
    Amount: Decimal | float | None
    Company: str | None
    Category: str | None
    Institution: str | None
    TransactionType: str | None
    Name: str | None
    UserId: str | None
    FromName: str | None
    FromEmail: str | None
    ToName: str | None
    ToEmail: str | None
    Subject: str | None
    Body: str | None
    TransactionHash: str
    CategoryAudit: dict[str, Any]
    ExtractionAudit: dict[str, Any]
    TransactionContext: dict[str, Any]
    Ignored: bool
    Comment: str | None
    DeletedAt: str | None
    StatementSource: str | None
    CreatedAt: str


@runtime_checkable
class ITransactionsDB(Protocol):
    """Contract for TransactionsDB and TransactionsDBLocal."""

    def add_transaction(
        self,
        transaction_data: dict[str, Any],
        category_audit: dict[str, Any] | None = ...,
        extraction_audit: dict[str, Any] | None = ...,
    ) -> str | bool | None: ...
    def add_statement_transaction(self, txn_data: dict[str, Any], audit_source: str = ...) -> str | bool | None: ...
    def update_category(
        self, forwarded_to: str, date_file_name: str, new_category: str, source: str = ...
    ) -> str | None: ...
    def mark_category_reviewed(self, forwarded_to: str, date_file_name: str, source: str = ...) -> None: ...
    def enrich_transaction(
        self,
        forwarded_to: str,
        date_file_name: str,
        new_company: str,
        new_category: str,
        source: str = ...,
        statement_source: str | None = ...,
    ) -> dict[str, Any] | None:
        """Enrich company/category from statement data.

        Company (and statement_source) always update; the category is preserved
        when it was set manually or when the incoming category is the
        ``miscellaneous`` fallback and the existing one is real. The returned
        dict carries ``category_preserved``.
        """
        ...

    def update_fields(
        self,
        forwarded_to: str,
        date_file_name: str,
        fields: dict[str, Any],
        category: str | None = ...,
    ) -> dict[str, Any] | None: ...
    def update_context(self, forwarded_to: str, date_file_name: str, context: dict[str, Any]) -> None: ...
    def set_ignored(self, forwarded_to: str, date_file_name: str, ignored: bool) -> bool | None: ...
    def set_deleted(self, forwarded_to: str, date_file_name: str, deleted: bool) -> bool | str | None: ...
    def permanently_delete(self, forwarded_to: str, date_file_name: str) -> TransactionItem | None: ...
    def set_comment(self, forwarded_to: str, date_file_name: str, comment: str | None) -> str | None: ...
    def get_item(self, forwarded_to: str, date_file_name: str) -> TransactionItem | None: ...
    def scan_by_category(self, category: str) -> list[TransactionItem]: ...
    def count_by_category(self, category: str) -> int: ...
    def query_month_partition(self, forwarded_to: str, year_month: str) -> list[TransactionItem]: ...
    def get_latest_date_file_name(self, year_month: str | None = ...) -> str | None: ...
    def get_recent_audits(self, limit: int = ...) -> list[dict[str, Any]]: ...
    def batch_update_category(self, items: list[dict[str, Any]], new_category: str, source: str = ...) -> int: ...
    def bulk_add_transactions(
        self,
        rows: list[dict[str, Any]],
        # Narrower signatures on concrete classes (e.g. Literal["skip", ...])
        # must remain substitutable, so the protocol accepts any object.
        strategy: Any = ...,
    ) -> dict[str, int]: ...
    def scan_all_transactions(self) -> list[TransactionItem]: ...
    def find_date_file_name_by_hash(self, forwarded_to: str, transaction_hash: str) -> str | None: ...


@runtime_checkable
class IBudgetService(Protocol):
    """Contract for BudgetService and BudgetServiceLocal."""

    def get_targets(self, year: int) -> dict[str, Any] | None: ...
    def get_groups(self, year: int) -> dict[str, Any] | None: ...
    def put_targets(self, year: int, data: dict[str, Any], expected_version: int | None) -> int: ...
    def put_groups(self, year: int, data: dict[str, Any], expected_version: int | None) -> int: ...
    def get_historical_averages(self, spending_summary: "ISpendingSummary", months: int = ...) -> dict[str, Any]: ...
    def get_category_anomalies(
        self,
        spending_summary: "ISpendingSummary",
        year_month: str,
        months: int = ...,
        annotated_amounts: dict[str, float] | None = ...,
    ) -> list[dict[str, Any]]: ...
    def invalidate_cache(self) -> None: ...
    def infer_category_type(
        self, months_active: int, months_total: int, coefficient_of_variation: float | None = ...
    ) -> str: ...


@runtime_checkable
class ISpendingSummary(Protocol):
    """Contract for SpendingSummary and SpendingSummaryLocal."""

    def get_summary(self, year_month: str) -> dict[str, Any]: ...
    def get_summary_with_comparison(self, year_month: str) -> dict[str, Any]: ...
    def query_month(
        self,
        year_month: str,
        projection: str | None = ...,
        expression_names: dict[str, str] | None = ...,
    ) -> list[TransactionItem]: ...
    def aggregate(self, items: Sequence[Mapping[str, Any]]) -> dict[str, Any]: ...


@runtime_checkable
class IOverrideService(Protocol):
    """Contract for OverrideService and OverrideServiceLocal."""

    def get_overrides(self) -> dict[str, Any] | None: ...
    def lookup_category(self, company: str, aliases: dict[str, str] | None = None) -> str | None: ...
    def put_override(self, company: str, category: str) -> int: ...
    def delete_override(self, company: str) -> int: ...
    def put_all_overrides(self, data: dict[str, Any], expected_version: int | None) -> int: ...
    def consolidate_overrides(self, canonical_company: str, canonical_category: str, members: list[str]) -> int: ...
    def dismiss_suggestion(self, company: str, category: str) -> None: ...
    def undismiss_suggestion(self, key: str) -> None: ...


@runtime_checkable
class IIgnoreRuleService(Protocol):
    """Contract for IgnoreRuleService and IgnoreRuleServiceLocal."""

    def get_rules(self) -> dict[str, Any] | None: ...
    def get_patterns(self) -> list[str]: ...
    def matches(self, company: str, aliases: dict[str, str] | None = None) -> Any: ...
    def add_rule(self, pattern: str) -> int: ...
    def delete_rule(self, pattern: str) -> int: ...
    def put_all_rules(self, patterns: list[str], expected_version: int | None) -> int: ...
    def get_dismissed(self) -> dict[str, Any]: ...
    def list_dismissed(self) -> list[dict[str, str]]: ...
    def dismiss_suggestion(self, merchant: str) -> None: ...
    def undismiss_suggestion(self, merchant: str) -> None: ...


@runtime_checkable
class ICategoryService(Protocol):
    """Contract for CategoryService and CategoryServiceLocal."""

    def get_categories(self) -> dict[str, Any] | None: ...
    def get_categories_list(self) -> list[str]: ...
    def add_category(self, name: str) -> int: ...
    def rename_category(self, old_name: str, new_name: str) -> int: ...
    def delete_category(self, name: str) -> int: ...
    def put_all_categories(self, categories: list[str], expected_version: int | None) -> int: ...


@runtime_checkable
class IMerchantAliasService(Protocol):
    """Contract for MerchantAliasService and MerchantAliasServiceLocal."""

    def get_aliases(self) -> dict[str, Any] | None: ...
    def get_aliases_map(self) -> dict[str, str]: ...
    def put_alias(self, raw_name: str, canonical_name: str) -> int: ...
    def delete_alias(self, raw_name: str) -> int: ...
    def put_all_aliases(self, data: dict[str, Any], expected_version: int | None) -> int: ...


@runtime_checkable
class IParseFailureStore(Protocol):
    """Contract for ParseFailureStore and ParseFailureStoreLocal."""

    def record_failure(self, failure: dict[str, Any]) -> str: ...
    def get_failure(self, failure_id: str) -> dict[str, Any] | None: ...
    def list_failures(self, status: str | None = ..., limit: int = ...) -> list[dict[str, Any]]: ...
    # Like list_failures but keeps email_json (same shape as get_failure) so a
    # bulk consumer can filter and retry in one pass without a per-id re-query.
    def list_failures_full(self, status: str | None = ..., limit: int = ...) -> list[dict[str, Any]]: ...
    def set_status(self, failure_id: str, status: str, recovered_date_file_name: str | None = ...) -> bool: ...
    def count_recent_quarantined(self, days: int = ...) -> int: ...
    def has_other_recent_failure(self, institution: str, hours: int = ...) -> bool: ...
    # Map each non-null detected institution to its most recent received_at
    # (any status) — arrival evidence for the coverage service's quiet detection.
    def latest_received_by_institution(self) -> dict[str, str]: ...


@runtime_checkable
class IActivityStore(Protocol):
    """Contract for ActivityStore and ActivityStoreLocal.

    Append-only agent-activity ledger: entries are recorded once and never
    updated or deleted, save for the single ``mark_reverted`` marker that
    records that a later entry undid this one. There is deliberately no
    ``update``/``delete`` method — the append-only shape is the point.
    """

    def record(self, entry: dict[str, Any]) -> str: ...
    def list_entries(
        self,
        principal: str | None = ...,
        since: str | None = ...,
        operation: str | None = ...,
        limit: int = ...,
        principal_kind: str | None = ...,
    ) -> list[dict[str, Any]]: ...
    def get_entry(self, entry_id: str) -> dict[str, Any] | None: ...
    def mark_reverted(self, entry_id: str, reverted_by_entry_id: str, ts: str | None = ...) -> None: ...


@runtime_checkable
class ICategoryIconService(Protocol):
    """Contract for CategoryIconService and CategoryIconServiceLocal."""

    def get_icons(self) -> dict[str, Any] | None: ...
    def get_icons_map(self) -> dict[str, str]: ...
    def set_icon(self, category: str, icon_name: str) -> int: ...
    def clear_icon(self, category: str) -> int: ...
    def rename_category(self, old_name: str, new_name: str) -> int: ...
    def delete_category(self, name: str) -> int: ...
