// Docs coverage gate for the docs-site (docs-site/src/content/docs/).
//
// Fails when the docs, the app, and the screenshot pipeline drift apart:
//   A. every hand-written .md/.mdx collection page is registered in the
//      docs-site sidebar (astro.config.mjs) AND in the llms.txt sections
//      (docs-site/scripts/generate-llms-txt.mjs) — both lists are manual.
//      Synced pages (generated from /docs/ by sync-content.mjs) are excluded;
//      their `dest:` slugs are read from that script, not duplicated here;
//   B. every route in frontend/src/App.tsx is either screenshotted
//      (scripts/media/docs_screenshots.manifest.ts) or explicitly waived below —
//      a new app page fails this gate until it is documented or waived;
//   C. every ThemedScreenshot id referenced in content has both -light and
//      -dark WebP files, every manifest id is referenced by some page, and
//      no screenshot file is orphaned;
//   D. every docs/media/readme/ image README.md references exists on disk
//      (those come from `make marketing-screenshots`).
//
// Run: node scripts/checks/check_docs_coverage.mjs   (from the repo root; no deps)

import { readFileSync, readdirSync } from "node:fs";
import { join, relative, sep } from "node:path";

const failures = [];
const read = (p) => readFileSync(p, "utf8");

// Routes documented in prose but deliberately not screenshotted (demo shows a
// "configure locally" callout, the route redirects, or the page is a shell).
const WAIVED_ROUTES = {
  "/transactions/trash": "demo gates the trash behind a configure-locally callout",
  "/statements": "self-hosted only; demo shows a callout, documented without a screenshot",
  "/budgets/edit": "covered by the budget-edit screenshot (same manifest id)",
  "/categorize": "covered by the categorize screenshot (same manifest id)",
  "/settings": "index route redirects to /settings/display",
  "/settings/navigation": "documented in prose on the settings page",
  "/settings/timezone": "documented in prose on the settings page",
  "/settings/features": "documented in prose on the settings page",
  "/settings/intelligence": "self-hosted only; demo shows a locked card",
  "/settings/password": "hidden in demo; documented in prose",
  "/settings/sessions": "hidden in demo; documented in prose",
  "/settings/system": "documented in prose on the settings page",
  "/settings/backup": "disabled in demo; documented in prose",
  "*": "catch-all redirect, nothing to document",
};

// --- gather inputs -----------------------------------------------------------

const docsRoot = "docs-site/src/content/docs";
const usingDir = `${docsRoot}/using`;
const pages = readdirSync(usingDir).filter((f) => f.endsWith(".mdx"));

const sidebar = read("docs-site/astro.config.mjs");
const llms = read("docs-site/scripts/generate-llms-txt.mjs");
const manifest = read("scripts/media/docs_screenshots.manifest.ts");
const appTsx = read("frontend/src/App.tsx");

const shotsDir = "docs-site/src/assets/screenshots";
const shotFiles = readdirSync(shotsDir).filter((f) => f.endsWith(".webp"));

// --- A: every hand-written collection page is registered ---------------------
// Enforces sidebar (astro.config.mjs) + llms.txt (generate-llms-txt.mjs) for
// every hand-written .md/.mdx under src/content/docs/ — both lists are manual.
// Synced pages (generated by sync-content.mjs from /docs/) are excluded: their
// registration is enforced at the source, and their `dest:` slugs are parsed
// out of that script rather than duplicated here.

// Slugs deliberately kept out of the docs-site sidebar (still enforced in llms).
const SIDEBAR_EXEMPT = new Set(["agent-guide"]);

const syncedDests = new Set(
  [...read("docs-site/scripts/sync-content.mjs").matchAll(/dest:\s*['"]([^'"]+)['"]/g)].map(
    (m) => m[1],
  ),
);

// Recursively list every .md/.mdx file under the docs content collection.
const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = join(dir, e.name);
    if (e.isDirectory()) return walk(full);
    return /\.mdx?$/.test(e.name) ? [full] : [];
  });

const contentSlugs = [];
for (const file of walk(docsRoot)) {
  const rel = relative(docsRoot, file).split(sep).join("/");
  if (syncedDests.has(rel)) continue; // synced page — enforced at its /docs/ source
  // slug: drop the extension; an `index` file maps to its directory, except the
  // root index.mdx which keeps the slug 'index'.
  let slug = rel.replace(/\.mdx?$/, "");
  if (slug.endsWith("/index")) slug = slug.slice(0, -"/index".length);
  contentSlugs.push(slug);
}

for (const slug of contentSlugs) {
  if (!SIDEBAR_EXEMPT.has(slug) && !sidebar.includes(`'${slug}'`))
    failures.push(`A: ${slug} missing from docs-site/astro.config.mjs sidebar`);
  if (!llms.includes(`'${slug}'`))
    failures.push(`A: ${slug} missing from generate-llms-txt.mjs sections`);
}

// --- B: app routes vs screenshot manifest ------------------------------------

// Absolute paths come straight from path="..."; the only nested group in
// App.tsx is /settings, so bare child paths are prefixed with it.
const routes = new Set();
for (const m of appTsx.matchAll(/path="([^"]+)"/g)) {
  const p = m[1];
  routes.add(p.startsWith("/") || p === "*" ? p : `/settings/${p}`);
}

const manifestPaths = new Set(
  [...manifest.matchAll(/path:\s*"([^"]+)"/g)].map((m) =>
    m[1].replace(/^\/demo/, "").replace(/\?.*$/, "") || "/",
  ),
);

for (const route of routes) {
  if (manifestPaths.has(route)) continue;
  if (route in WAIVED_ROUTES) continue;
  failures.push(
    `B: app route ${route} has no screenshot manifest entry and no waiver — ` +
      `document it (or waive it in scripts/checks/check_docs_coverage.mjs)`,
  );
}

// --- C: screenshot ids — content ↔ manifest ↔ files --------------------------

const referencedIds = new Set();
for (const f of pages) {
  for (const m of read(join(usingDir, f)).matchAll(/<ThemedScreenshot\s+id="([a-z-]+)"/g))
    referencedIds.add(m[1]);
}
const manifestIds = new Set([...manifest.matchAll(/id:\s*"([a-z-]+)"/g)].map((m) => m[1]));
const fileIds = new Set(shotFiles.map((f) => f.replace(/-(light|dark)\.webp$/, "")));

for (const id of referencedIds) {
  for (const theme of ["light", "dark"])
    if (!shotFiles.includes(`${id}-${theme}.webp`))
      failures.push(`C: content references id "${id}" but ${id}-${theme}.webp is missing (run make docs-screenshots)`);
  if (!manifestIds.has(id))
    failures.push(`C: content references id "${id}" but it is not in docs_screenshots.manifest.ts`);
}
for (const id of manifestIds)
  if (!referencedIds.has(id))
    failures.push(`C: manifest id "${id}" is captured but no docs page references it`);
for (const id of fileIds)
  if (!manifestIds.has(id))
    failures.push(`C: orphan screenshot files for id "${id}" (not in the manifest)`);

// --- D: README + marketing screenshot files exist -----------------------------
// These are produced by `make marketing-screenshots`; a renamed slug or a
// deleted asset would otherwise 404 silently on GitHub / the landing page.

const readme = read("README.md");
const readmeRefs = [...readme.matchAll(/(?:src|srcset)="(docs\/static\/readme\/[^"\s]+)"/g)].map(
  (m) => m[1],
);
for (const ref of new Set(readmeRefs)) {
  try {
    readFileSync(ref);
  } catch {
    failures.push(`D: README.md references ${ref} but the file does not exist (run make marketing-screenshots)`);
  }
}

const marketingAssets = readdirSync("frontend/src/marketing/assets").filter((f) =>
  f.startsWith("screenshot-"),
);
for (const f of marketingAssets)
  if (!f.endsWith(".webp"))
    failures.push(`D: unexpected non-webp marketing screenshot asset: ${f}`);

// --- report -------------------------------------------------------------------

if (failures.length) {
  console.error(`docs coverage: ${failures.length} failure(s)`);
  for (const f of failures) console.error(`  - ${f}`);
  process.exit(1);
}
console.log(
  `docs coverage: ok — ${contentSlugs.length} pages registered, ` +
    `${routes.size} app routes covered or waived, ${referencedIds.size} screenshot ids consistent`,
);
