"""Pydantic request/response schemas for the finance dashboard API."""

from src.api.models.activity import (
    ActivityEntry,
    ActivityListResponse,
    RevertResponse,
    WhoamiResponse,
)
from src.api.models.attachments import (
    AttachmentDeleteResponse,
    AttachmentListResponse,
    AttachmentResponse,
    LinkAttachmentRequest,
    ReceiptCandidate,
    ReceiptCandidatesResponse,
)
from src.api.models.budget import (
    BudgetCategoryConfig,
    BudgetCategoryConfigInput,
    BudgetConfigResponse,
    BudgetConfigUpdateRequest,
    BudgetGroupConfig,
    BudgetStatusResponse,
    CategoryPaceDetail,
    GroupPace,
    GroupsResponse,
    GroupsUpdateRequest,
    HistoricalAveragesResponse,
    HistoricalCategoryAverage,
    PaceStatus,
    UnbudgetedCategory,
)
from src.api.models.categories import (
    CategoriesManagementResponse,
    CategoryAddRequest,
    CategoryDeleteResponse,
    CategoryGroupUpdateRequest,
    CategoryGroupUpdateResponse,
    CategoryIconsResponse,
    CategoryRenameRequest,
    CategoryRenameResponse,
    CategoryUsageResponse,
    CategoryWithGroup,
    SetCategoryIconRequest,
)
from src.api.models.config import (
    AppConfigResponse,
    AppConfigUpdateRequest,
    TestOpenAIResponse,
    TestS3BackupResponse,
)
from src.api.models.coverage import (
    CaptureBucket,
    CaptureBucketInstitution,
    CaptureBucketType,
    CaptureSummary,
    CoverageInstitution,
    CoverageResponse,
)
from src.api.models.daily_summary import (
    DaySummariesResponse,
    DaySummaryGenerateRequest,
    DaySummaryGenerateResponse,
    DaySummaryStatusResponse,
)
from src.api.models.data import (
    ConfigPreview,
    ImportCommitRequest,
    ImportPreviewCounts,
    ImportPreviewResponse,
    ImportPreviewSample,
    ImportResult,
    S3BackupStatusResponse,
)
from src.api.models.health import (
    HealthResponse,
    HealthStatus,
)
from src.api.models.ignore_rules import (
    DismissedIgnoreRuleSuggestion,
    DismissedIgnoreRuleSuggestionsResponse,
    IgnoreRuleAddRequest,
    IgnoreRuleApplyRequest,
    IgnoreRuleApplyResponse,
    IgnoreRuleApplyResult,
    IgnoreRuleDeleteResponse,
    IgnoreRuleEntry,
    IgnoreRuleListResponse,
    IgnoreRuleSuggestion,
    IgnoreRuleSuggestionDismissRequest,
    IgnoreRuleSuggestionDismissResponse,
    IgnoreRuleSuggestionsResponse,
    IgnoreRuleSuggestionUndismissResponse,
)
from src.api.models.income_statement import (
    ExpenseCategoryRow,
    ExpenseSectionResponse,
    IncomeCompanyRow,
    IncomeSectionResponse,
    IncomeStatementResponse,
    ProjectionResponse,
)
from src.api.models.ingestion import (
    ManualTransactionRequest,
    ManualTransactionResponse,
    UploadEmlResponse,
)
from src.api.models.insights import (
    BriefingFigure,
    BriefingValidation,
    BriefingValidationSummary,
    FixedCharge,
    InsightsContextResponse,
    InsightsGenerateResponse,
    InsightsStatusResponse,
    LargestTransaction,
    MonthProgress,
    PaceBlock,
    PaceCategory,
    PaceCeiling,
    PaceUnbudgeted,
    PreviousBriefing,
    RecurringAnnualCategory,
    SameMonthLastYear,
    SavedInsightDetail,
    SavedInsightItem,
    SavedInsightListResponse,
    SuspectedIgnored,
)
from src.api.models.journal import (
    JournalDay,
    JournalResponse,
)
from src.api.models.merchant_aliases import (
    MerchantAliasEntry,
    MerchantAliasListResponse,
    MerchantAliasMutationResponse,
    MerchantAliasPutRequest,
)
from src.api.models.merchants import (
    MerchantIntelligenceResponse,
    MerchantIntelligenceSummary,
    MerchantPriceChange,
    MerchantRecord,
)
from src.api.models.overrides import (
    DismissSuggestionRequest,
    OverrideConsolidateRequest,
    OverrideConsolidateResponse,
    OverrideDeleteResponse,
    OverrideDuplicateGroup,
    OverrideDuplicateMember,
    OverrideDuplicatesResponse,
    OverrideEntry,
    OverrideListResponse,
    OverrideMatchCandidate,
    OverrideMatchResponse,
    OverridePutRequest,
    OverrideSuggestion,
    OverrideSuggestionsResponse,
    SuggestionDismissResponse,
    SuggestionUndismissResponse,
)
from src.api.models.parse_failures import (
    DismissResponse,
    FixtureFromFailureRequest,
    FixtureFromFailureResponse,
    ManualResolveRequest,
    ManualResolveResponse,
    ParseFailureDetail,
    ParseFailureListResponse,
    ParseFailureSummary,
    RetryAllRequest,
    RetryAllResponse,
    RetryResponse,
)
from src.api.models.search import (
    SearchByFilterRequest,
    SearchResponse,
    SearchSummary,
)
from src.api.models.statements import (
    AmbiguousItem,
    BulkActionUpdateItem,
    BulkTransactionUpdate,
    BulkTransactionUpdateResponse,
    ImportAction,
    ImportActionType,
    ImportByIdRequest,
    ImportRequest,
    ImportResponse,
    MatchedItem,
    NewItem,
    PreviouslyImportedItem,
    RawStatementTxn,
    ReconcileSummary,
    StatementDbMatch,
    StatementDbMatchWithType,
    StatementDeleteResponse,
    StatementDetailResponse,
    StatementListResponse,
    StatementMetadata,
    StatementSummaryItem,
    StatementTransaction,
    StatementTransactionItem,
    StatementUploadResponse,
    SuspectedDuplicateItem,
    TransactionActionUpdate,
    TransactionActionUpdateResponse,
)
from src.api.models.summary import (
    CategorySummary,
    CompanySummary,
    DepositSourceSummary,
    ExpectedChargeInfo,
    MonthPaceBreakdown,
    MonthPaceInfo,
    MonthSummary,
    SummaryComparisonResponse,
    TopCategory,
    TrendMonthEntry,
    TrendResponse,
)
from src.api.models.tax import (
    TaxEvidenceCounts,
    TaxLineOption,
    TaxLineResponse,
    TaxLinesResponse,
    TaxOverrideRequest,
    TaxPackResponse,
    TaxPackTransaction,
)
from src.api.models.transactions import (
    AttentionListResponse,
    BulkCategoryUpdateItem,
    BulkCategoryUpdateRequest,
    BulkCategoryUpdateResponse,
    BulkCategoryUpdateResult,
    CategoriesResponse,
    CategoryAudit,
    CategoryUpdateRequest,
    CategoryUpdateResponse,
    CombinedTransactionsResponse,
    CommentRequest,
    CommentResponse,
    DeleteRequest,
    DeleteResponse,
    ExtractionAudit,
    IgnoreRequest,
    IgnoreResponse,
    LatestTimestampResponse,
    PermanentDeleteResponse,
    ReviewResponse,
    TransactionContext,
    TransactionDetailResponse,
    TransactionFieldsOldValues,
    TransactionFieldsUpdateRequest,
    TransactionFieldsUpdateResponse,
    TransactionListResponse,
    TransactionResponse,
)

__all__ = [  # noqa: RUF022 — grouped by module for readability, not strict alpha order
    # activity
    "ActivityEntry",
    "ActivityListResponse",
    "RevertResponse",
    "WhoamiResponse",
    # attachments
    "AttachmentDeleteResponse",
    "AttachmentListResponse",
    "AttachmentResponse",
    "LinkAttachmentRequest",
    "ReceiptCandidate",
    "ReceiptCandidatesResponse",
    # budget
    "BudgetCategoryConfig",
    "BudgetCategoryConfigInput",
    "BudgetConfigResponse",
    "BudgetConfigUpdateRequest",
    "BudgetGroupConfig",
    "BudgetStatusResponse",
    "CategoryPaceDetail",
    "GroupPace",
    "GroupsResponse",
    "GroupsUpdateRequest",
    "HistoricalAveragesResponse",
    "HistoricalCategoryAverage",
    "PaceStatus",
    "UnbudgetedCategory",
    # categories
    "CategoriesManagementResponse",
    "CategoryAddRequest",
    "CategoryDeleteResponse",
    "CategoryGroupUpdateRequest",
    "CategoryGroupUpdateResponse",
    "CategoryIconsResponse",
    "CategoryRenameRequest",
    "CategoryRenameResponse",
    "CategoryUsageResponse",
    "CategoryWithGroup",
    "SetCategoryIconRequest",
    # config
    "AppConfigResponse",
    "AppConfigUpdateRequest",
    "TestOpenAIResponse",
    "TestS3BackupResponse",
    # coverage
    "CaptureBucket",
    "CaptureBucketInstitution",
    "CaptureBucketType",
    "CaptureSummary",
    "CoverageInstitution",
    "CoverageResponse",
    # data
    "ConfigPreview",
    "ImportCommitRequest",
    "ImportPreviewCounts",
    "ImportPreviewResponse",
    "ImportPreviewSample",
    "ImportResult",
    "S3BackupStatusResponse",
    # daily_summary
    "DaySummariesResponse",
    "DaySummaryGenerateRequest",
    "DaySummaryGenerateResponse",
    "DaySummaryStatusResponse",
    # health
    "HealthResponse",
    "HealthStatus",
    # ignore_rules
    "DismissedIgnoreRuleSuggestion",
    "DismissedIgnoreRuleSuggestionsResponse",
    "IgnoreRuleAddRequest",
    "IgnoreRuleApplyRequest",
    "IgnoreRuleApplyResponse",
    "IgnoreRuleApplyResult",
    "IgnoreRuleDeleteResponse",
    "IgnoreRuleEntry",
    "IgnoreRuleListResponse",
    "IgnoreRuleSuggestion",
    "IgnoreRuleSuggestionDismissRequest",
    "IgnoreRuleSuggestionDismissResponse",
    "IgnoreRuleSuggestionUndismissResponse",
    "IgnoreRuleSuggestionsResponse",
    # income_statement
    "ExpenseCategoryRow",
    "ExpenseSectionResponse",
    "IncomeCompanyRow",
    "IncomeSectionResponse",
    "IncomeStatementResponse",
    "ProjectionResponse",
    # journal
    "JournalDay",
    "JournalResponse",
    # ingestion
    "ManualTransactionRequest",
    "ManualTransactionResponse",
    "UploadEmlResponse",
    # insights
    "BriefingFigure",
    "BriefingValidation",
    "BriefingValidationSummary",
    "FixedCharge",
    "InsightsContextResponse",
    "InsightsGenerateResponse",
    "InsightsStatusResponse",
    "LargestTransaction",
    "MonthProgress",
    "PaceBlock",
    "PaceCategory",
    "PaceCeiling",
    "PaceUnbudgeted",
    "PreviousBriefing",
    "RecurringAnnualCategory",
    "SameMonthLastYear",
    "SavedInsightDetail",
    "SavedInsightItem",
    "SavedInsightListResponse",
    "SuspectedIgnored",
    # merchant_aliases
    "MerchantAliasEntry",
    "MerchantAliasListResponse",
    "MerchantAliasMutationResponse",
    "MerchantAliasPutRequest",
    # merchants
    "MerchantIntelligenceResponse",
    "MerchantIntelligenceSummary",
    "MerchantPriceChange",
    "MerchantRecord",
    # overrides
    "DismissSuggestionRequest",
    "OverrideConsolidateRequest",
    "OverrideConsolidateResponse",
    "OverrideDeleteResponse",
    "OverrideDuplicateGroup",
    "OverrideDuplicateMember",
    "OverrideDuplicatesResponse",
    "OverrideEntry",
    "OverrideListResponse",
    "OverrideMatchCandidate",
    "OverrideMatchResponse",
    "OverridePutRequest",
    "OverrideSuggestion",
    "OverrideSuggestionsResponse",
    "SuggestionDismissResponse",
    "SuggestionUndismissResponse",
    # parse_failures
    "DismissResponse",
    "FixtureFromFailureRequest",
    "FixtureFromFailureResponse",
    "ManualResolveRequest",
    "ManualResolveResponse",
    "ParseFailureDetail",
    "ParseFailureListResponse",
    "ParseFailureSummary",
    "RetryAllRequest",
    "RetryAllResponse",
    "RetryResponse",
    # search
    "SearchByFilterRequest",
    "SearchResponse",
    "SearchSummary",
    # statements
    "AmbiguousItem",
    "BulkActionUpdateItem",
    "BulkTransactionUpdate",
    "BulkTransactionUpdateResponse",
    "ImportAction",
    "ImportActionType",
    "ImportByIdRequest",
    "ImportRequest",
    "ImportResponse",
    "MatchedItem",
    "NewItem",
    "PreviouslyImportedItem",
    "RawStatementTxn",
    "ReconcileSummary",
    "StatementDbMatch",
    "StatementDbMatchWithType",
    "StatementDeleteResponse",
    "StatementDetailResponse",
    "StatementListResponse",
    "StatementMetadata",
    "StatementSummaryItem",
    "StatementTransaction",
    "StatementTransactionItem",
    "StatementUploadResponse",
    "SuspectedDuplicateItem",
    "TransactionActionUpdate",
    "TransactionActionUpdateResponse",
    # summary
    "CategorySummary",
    "CompanySummary",
    "DepositSourceSummary",
    "ExpectedChargeInfo",
    "MonthPaceBreakdown",
    "MonthPaceInfo",
    "MonthSummary",
    "SummaryComparisonResponse",
    "TopCategory",
    "TrendMonthEntry",
    "TrendResponse",
    # tax
    "TaxEvidenceCounts",
    "TaxLineOption",
    "TaxLineResponse",
    "TaxLinesResponse",
    "TaxOverrideRequest",
    "TaxPackResponse",
    "TaxPackTransaction",
    # transactions
    "AttentionListResponse",
    "BulkCategoryUpdateItem",
    "BulkCategoryUpdateRequest",
    "BulkCategoryUpdateResponse",
    "BulkCategoryUpdateResult",
    "CategoriesResponse",
    "CategoryAudit",
    "CategoryUpdateRequest",
    "CategoryUpdateResponse",
    "CombinedTransactionsResponse",
    "CommentRequest",
    "CommentResponse",
    "DeleteRequest",
    "DeleteResponse",
    "ExtractionAudit",
    "IgnoreRequest",
    "IgnoreResponse",
    "LatestTimestampResponse",
    "PermanentDeleteResponse",
    "ReviewResponse",
    "TransactionContext",
    "TransactionDetailResponse",
    "TransactionFieldsOldValues",
    "TransactionFieldsUpdateRequest",
    "TransactionFieldsUpdateResponse",
    "TransactionListResponse",
    "TransactionResponse",
]
