import {
  Baby,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Calculator,
  Car,
  Dumbbell,
  Film,
  Fuel,
  Gift,
  GraduationCap,
  Hammer,
  Heart,
  Home,
  Laptop,
  Landmark,
  MoreHorizontal,
  Palette,
  Phone,
  Plane,
  Receipt,
  Repeat,
  Shield,
  Shirt,
  ShoppingCart,
  Sofa,
  Sparkles,
  Stethoscope,
  Truck,
  Users,
  Utensils,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { iconByName } from "@/lib/iconCatalog";

const MAP: Record<string, LucideIcon> = {
  "accounting services": Calculator,
  "automotive maintenance": Wrench,
  automotive: Car,
  "baby items": Baby,
  "car payment": Car,
  "charitable giving": Heart,
  childcare: Baby,
  cleaners: Brush,
  clothing: Shirt,
  "communication/cell": Phone,
  computer: Laptop,
  counselling: Brain,
  dining: Utensils,
  education: GraduationCap,
  entertainment: Film,
  furniture: Sofa,
  gasoline: Fuel,
  "general transportation": Car,
  gifts: Gift,
  groceries: ShoppingCart,
  "health care": Stethoscope,
  health: Heart,
  hobbies: Palette,
  "house maintenance": Hammer,
  "household items": Home,
  housing: Home,
  "hygiene/personal care": Sparkles,
  insurance: Shield,
  internet: Wifi,
  "liquor/beer/wine": Wine,
  "major property upgrades": Hammer,
  medical: Heart,
  "misc. car expense": Car,
  mortgage: Home,
  "moving expense": Truck,
  office: Briefcase,
  "professional membership": Users,
  "professional services": Briefcase,
  rent: Home,
  "restaurant/dining": Utensils,
  restaurants: Utensils,
  "service charges/fees": Receipt,
  "sports and recreation": Dumbbell,
  strata: Building2,
  subscriptions: Repeat,
  taxes: Landmark,
  technology: Laptop,
  transportation: Car,
  travel: Plane,
  tuition: GraduationCap,
  utilities: Zap,
  vacation: Plane,
};

export function iconForCategory(
  category: string | null | undefined,
  overrides?: Record<string, string>
): LucideIcon {
  if (!category) return MoreHorizontal;
  const key = category.toLowerCase();
  const override = overrides?.[key];
  if (override) return iconByName(override);
  return MAP[key] ?? MoreHorizontal;
}
