import {
  Activity,
  Ambulance,
  Apple,
  Armchair,
  Baby,
  Banknote,
  Bath,
  BedDouble,
  Beef,
  Beer,
  Bike,
  Book,
  Brain,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cable,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarFront,
  Cat,
  ChefHat,
  Clipboard,
  Clock,
  Coffee,
  Coins,
  Contact,
  Cookie,
  CreditCard,
  Croissant,
  Dog,
  DollarSign,
  DoorOpen,
  Droplet,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  IceCream,
  Key,
  Keyboard,
  Lamp,
  Landmark,
  Laptop,
  Library,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  Microwave,
  Monitor,
  MoreHorizontal,
  Music,
  Music2,
  Notebook,
  Package,
  Palette,
  ParkingCircle,
  PartyPopper,
  PenTool,
  Pencil,
  PersonStanding,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Printer,
  Receipt,
  Refrigerator,
  Repeat,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  Settings,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Soup,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Syringe,
  Tag,
  Tent,
  Ticket,
  Train,
  TramFront,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  User,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  Warehouse,
  WashingMachine,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface IconCatalogEntry {
  name: string;
  icon: LucideIcon;
}

export interface IconCatalogGroup {
  group: string;
  icons: IconCatalogEntry[];
}

export const ICON_CATALOG: IconCatalogGroup[] = [
  {
    group: "Food & Drink",
    icons: [
      { name: "Utensils", icon: Utensils },
      { name: "Coffee", icon: Coffee },
      { name: "Pizza", icon: Pizza },
      { name: "Beef", icon: Beef },
      { name: "Sandwich", icon: Sandwich },
      { name: "Salad", icon: Salad },
      { name: "IceCream", icon: IceCream },
      { name: "Cookie", icon: Cookie },
      { name: "Wine", icon: Wine },
      { name: "Beer", icon: Beer },
      { name: "Apple", icon: Apple },
      { name: "Soup", icon: Soup },
      { name: "Croissant", icon: Croissant },
      { name: "Cake", icon: Cake },
      { name: "ChefHat", icon: ChefHat },
    ],
  },
  {
    group: "Transport",
    icons: [
      { name: "Car", icon: Car },
      { name: "CarFront", icon: CarFront },
      { name: "Fuel", icon: Fuel },
      { name: "Plane", icon: Plane },
      { name: "Train", icon: Train },
      { name: "TramFront", icon: TramFront },
      { name: "Bus", icon: Bus },
      { name: "Bike", icon: Bike },
      { name: "Ship", icon: Ship },
      { name: "Truck", icon: Truck },
      { name: "MapPin", icon: MapPin },
      { name: "ParkingCircle", icon: ParkingCircle },
    ],
  },
  {
    group: "Home",
    icons: [
      { name: "Home", icon: Home },
      { name: "Building", icon: Building },
      { name: "Building2", icon: Building2 },
      { name: "BedDouble", icon: BedDouble },
      { name: "Bath", icon: Bath },
      { name: "Sofa", icon: Sofa },
      { name: "Armchair", icon: Armchair },
      { name: "Lamp", icon: Lamp },
      { name: "Refrigerator", icon: Refrigerator },
      { name: "WashingMachine", icon: WashingMachine },
      { name: "Microwave", icon: Microwave },
      { name: "DoorOpen", icon: DoorOpen },
      { name: "Key", icon: Key },
      { name: "Warehouse", icon: Warehouse },
    ],
  },
  {
    group: "Money",
    icons: [
      { name: "DollarSign", icon: DollarSign },
      { name: "CreditCard", icon: CreditCard },
      { name: "Banknote", icon: Banknote },
      { name: "Landmark", icon: Landmark },
      { name: "Wallet", icon: Wallet },
      { name: "Receipt", icon: Receipt },
      { name: "PiggyBank", icon: PiggyBank },
      { name: "Coins", icon: Coins },
      { name: "Calculator", icon: Calculator },
      { name: "TrendingUp", icon: TrendingUp },
      { name: "TrendingDown", icon: TrendingDown },
      { name: "Scale", icon: Scale },
    ],
  },
  {
    group: "Shopping",
    icons: [
      { name: "ShoppingCart", icon: ShoppingCart },
      { name: "ShoppingBag", icon: ShoppingBag },
      { name: "Store", icon: Store },
      { name: "Gift", icon: Gift },
      { name: "Tag", icon: Tag },
      { name: "Package", icon: Package },
      { name: "Shirt", icon: Shirt },
      { name: "Footprints", icon: Footprints },
      { name: "Glasses", icon: Glasses },
      { name: "Watch", icon: Watch },
    ],
  },
  {
    group: "Tech",
    icons: [
      { name: "Laptop", icon: Laptop },
      { name: "Smartphone", icon: Smartphone },
      { name: "Monitor", icon: Monitor },
      { name: "Wifi", icon: Wifi },
      { name: "Phone", icon: Phone },
      { name: "Headphones", icon: Headphones },
      { name: "Gamepad2", icon: Gamepad2 },
      { name: "Printer", icon: Printer },
      { name: "Camera", icon: Camera },
      { name: "Tv", icon: Tv },
      { name: "Cable", icon: Cable },
      { name: "Keyboard", icon: Keyboard },
    ],
  },
  {
    group: "People",
    icons: [
      { name: "User", icon: User },
      { name: "Users", icon: Users },
      { name: "Baby", icon: Baby },
      { name: "Dog", icon: Dog },
      { name: "Cat", icon: Cat },
      { name: "Heart", icon: Heart },
      { name: "HandHeart", icon: HandHeart },
      { name: "UserPlus", icon: UserPlus },
      { name: "Contact", icon: Contact },
      { name: "PersonStanding", icon: PersonStanding },
    ],
  },
  {
    group: "Health",
    icons: [
      { name: "Stethoscope", icon: Stethoscope },
      { name: "HeartPulse", icon: HeartPulse },
      { name: "Pill", icon: Pill },
      { name: "Syringe", icon: Syringe },
      { name: "Activity", icon: Activity },
      { name: "Hospital", icon: Hospital },
      { name: "Ambulance", icon: Ambulance },
      { name: "Brain", icon: Brain },
      { name: "Dumbbell", icon: Dumbbell },
      { name: "Sparkles", icon: Sparkles },
    ],
  },
  {
    group: "Leisure",
    icons: [
      { name: "Film", icon: Film },
      { name: "Music", icon: Music },
      { name: "Music2", icon: Music2 },
      { name: "Guitar", icon: Guitar },
      { name: "Book", icon: Book },
      { name: "Palette", icon: Palette },
      { name: "Trophy", icon: Trophy },
      { name: "Tent", icon: Tent },
      { name: "Globe", icon: Globe },
      { name: "Map", icon: Map },
      { name: "Ticket", icon: Ticket },
      { name: "PartyPopper", icon: PartyPopper },
    ],
  },
  {
    group: "Work & Education",
    icons: [
      { name: "Briefcase", icon: Briefcase },
      { name: "GraduationCap", icon: GraduationCap },
      { name: "FileText", icon: FileText },
      { name: "Notebook", icon: Notebook },
      { name: "Pencil", icon: Pencil },
      { name: "PenTool", icon: PenTool },
      { name: "School", icon: School },
      { name: "Library", icon: Library },
      { name: "Clipboard", icon: Clipboard },
      { name: "Calendar", icon: Calendar },
    ],
  },
  {
    group: "Utilities & Other",
    icons: [
      { name: "Zap", icon: Zap },
      { name: "Lightbulb", icon: Lightbulb },
      { name: "Droplet", icon: Droplet },
      { name: "Flame", icon: Flame },
      { name: "Hammer", icon: Hammer },
      { name: "Wrench", icon: Wrench },
      { name: "Scissors", icon: Scissors },
      { name: "Brush", icon: Brush },
      { name: "Shield", icon: Shield },
      { name: "Lock", icon: Lock },
      { name: "Settings", icon: Settings },
      { name: "Clock", icon: Clock },
      { name: "Star", icon: Star },
      { name: "Repeat", icon: Repeat },
      { name: "MoreHorizontal", icon: MoreHorizontal },
    ],
  },
];

const BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  ICON_CATALOG.flatMap((g) => g.icons.map((i) => [i.name, i.icon]))
);

export const ALLOWED_ICON_NAMES: readonly string[] = Object.keys(BY_NAME);

export function iconByName(name: string | null | undefined): LucideIcon {
  if (!name) return MoreHorizontal;
  return BY_NAME[name] ?? MoreHorizontal;
}
